console.log("first")
console.log("second")

try{
   // let a=10;
console.log(a)
}

catch(err){
    console.log(err)
}

console.log("third")



function test(){
    console.log("test called")
}

test()


console.log("last")